language: python
python:
  - '3.6'

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="mychoice.travis"

script:
  - ./manage.py test
